name: Build and Deploy Backend

on:
  push:
    branches: [ main, test-CI/CD ]  # Ajout de main comme branche de déclenchement
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        # pip install pytest  # Commenté car les tests sont désactivés
    
    # Tests désactivés car ils nécessitent Ollama qui n'est pas disponible dans GitHub Actions
    # - name: Run tests
    #   run: |
    #     cd backend
    #     python -m pytest -v
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Configure Docker to use Google Cloud
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
        
    - name: Build and push backend Docker image
      run: |
        cd backend
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mediassist-images/backend:${{ github.sha }} .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mediassist-images/backend:${{ github.sha }}
        
        # Tag as latest
        docker tag ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mediassist-images/backend:${{ github.sha }} \
                  ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mediassist-images/backend:latest
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mediassist-images/backend:latest
        
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: mediassist-backend-with-sql
        image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mediassist-images/backend:${{ github.sha }}
        region: ${{ secrets.GCP_REGION }}
        cloudsql_instances: ${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:mediassist-db
        service_account_email: cloudrun-service-account@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
        allow_unauthenticated: true
        env_vars: |
          ENVIRONMENT=production
          GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}
          OLLAMA_HOST=https://ollama-gemma-bv5bumqn3a-ew.a.run.app